### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by henokkhm** [Kgomotso196/MyPortfolio#14]
In this code review, we have suggested the following changes:

- The navbar is not styled correctly for screens larger than 1710 pixels. Please remove the max-widths in your media queries to fix this issue.
- The paragraph in the hero section is not centered for screen sizes around 800-900 pixels. Please adjust the CSS to center the text.
- The font-size on the cards is only 7 pixels on some screen sizes, which may be too small to read. Please increase that to improve the user experience.

**Comment by Fombi-Favour** [comment]
The design is good 👍 but, the menu bar is so transparent.
![Issue](https://github.com/Kgomotso196/MyPortfolio/assets/77404317/9fa9a5c7-960e-4716-ac4a-661119257366)
Please kindly set the menu element with a background color and box shadow to eliminate the transparency 🙏
