### ISSUE TITLE
Peer to peer code review week 3 day 4

### ISSUE THREAD

**Issue by Rifat8080** [Kgomotso196/MyPortfolio#8]
You did a really great work on the project!🎉🎊
Still there need to be done small changes and updates.

- Link your navbar elements with ids so that when someone click them they navigate to that sections
- Make you scrolling button clickable with an id

**Comment by Shabiblac** [comment]
Great job ✔
You did great on the project!🎉🎊
Kindly try to add some transitions and animation to improve the user experience  😄

**Comment by olanikegloria** [comment]
Your work is really great 👍and I have not noticed any changes you need to make but according to the remaining partners you should add logo to the mobile version of your page ✨

**Comment by Rifat8080** [comment]
Overall  you did a really great work!🎊 I hope you will sort out these issues as soon as possible then you will be able launch your portfolio project perfectly.
