### ISSUE TITLE
Peer to peer code review.

### ISSUE THREAD

**Issue by sheldonwafula** [Kgomotso196/MyPortfolio#9]
Your code looks nice and you did excellent work.

**Comment by Fombi-Favour** [comment]
Your code and implementation is so awesome 👍 and I really like it 🎉. Opening the live output, I think there should be some changes.
On the `about` section, the tags are not centralized. Can you kindly look into it 🙏
![ok](https://github.com/Kgomotso196/MyPortfolio/assets/77404317/5448a56c-6556-4b14-843c-b82481546971)
